export const data = [
  {
    post:
      'At Vijay Ghat, paid tributes to Shastri Ji. India will never forget the valuable contribution of Shastri Ji. He was a stalwart who never deviated from his ideals and principles, come what may.',
    comments: [
      'A True Leader of the masses, rising from amongst them to the high office. Had Destiny not snatched him , He would have led us to Big Times. A Statesman to the Core.',
      'Many have forgotten sasthri ji and his contribution to our country...we should remember our leaders.',
      'One of the great leader India had,whose contribution remained hidden ,under the personal interest of a particular so called freedom fighters family deemed to be contributive for progress of country.',
      'Where is flood relief fund for karnataka sir..you completely forgot karnataka after getting 25 of 27 seats last election.',
      'Modiji please give flood relief fund to north karnataka,only Bihar is not in india we south people are also in India..',
      'The real old time PM of India. Unfortunate and mysterious that he left for unknown at an early age. India would have changed much earlier if he would have there to lead the country for longer time.',
      'Y not to Gandhi ji on his Birthday? Stop playing with emotions of people. I wan to go on a debate with u as a citizen of India.',
      'Bahut hi Mahan Lal Bahadur Shastri Ji',
      'But u forget live humans who suffered from flood in Karnataka , great 25 MPs?',
      "Yah so long the day was celebrated only as Gandhi Jayanthi, today it's Shastrijis birthday also thank you modiji for reminding great legend shastriji",
      'Great job prime minister Narendra Modi ji sir jai hind jai kishan tribute to Lal Bahadur Sastri ji Sat sat Namam jai hind',
      'Lal Bahadur Shastri - The Man who Loved India, but India did not love him back. He was a part of the Servant society of India, which believed in not accumulating wealth but work selflessly for the public and remain the servants of People.',
      'We know very well you are doing best part as others but try to understand as of now maximum sectors are in down position due to your strictness',
      'Can you explain all corruption has been finished from India',
      'Please note that every politician have more than black money to others',
    ],
  },
  {
    post:
      "GREAT news, Indian snooker fans...We're bringing you FREE live coverage of the big events this season!",
    comments: [
      "Because it's not available on Facebook live anyway??!! I've watched every tournament on Facebook live this year!! But yeah, good one, so generous.",
      'Best news I’ve heard all year!',
      'At last! Great News!',
      'Please make it happen for Malaysia fans! There are thousands of snooker fans unable to watching live match on Eurosport (subscription unavailable in this country)!',
      'Waiting Eagerly',
      'Bullshit!! How about streaming to Canada FFS.',
      'Because they are poor?',
      'Qnax Ybeq, great to see you as the face of India',
      'Why not in Pakistan?',
      'That’s great we don’t get snooker live in Southern Africa so glad to have access well done.',
      'About time.... Absolutely great news...',
      'Brilliant and Intelligent decision taken by World Snooker',
    ],
  },
  {
    post:
      "Our brand new Baize Watch challenge is tough. Can YOU beat defending English Open champion Stuart Bingham at 'Back to Black'?",
    comments: [
      'Just two pots shy for me compared to the world champ!',
      "I haven't played for years and I still think I could do more than 3",
      'Think it’s first attempt not 200th and submit the one you did best on.',
      'Morgan Dean absolute class this!',
      'Aaron, will have to give it a go on the next putting',
      'Rami Malik, challenge accepted?',
      'Idk if you guys know about century game (first person to score 100 wins) but this shot is one of My most perfect shots. I love to go all around the table for a second and third black and that is with other balls present on the table. I can pot an easy 5 or 6 blacks.',
      'I will just be two short of bingham',
      'Matt Kayley Neil Mcgovern Pete Pistol Cliffe new club challenge',
      'Zeeshan Ashraf wanna accept that?',
      'Ryan Woodward something to try',
    ],
  },
  {
    post:
      "Fancy finding out who Ronnie O'Sullivan and Judd Trump play on the opening day of the upcoming English Open?",
    comments: [
      "Bit clickbaity of you to make it look like trump is playing O'Sullivan haha.",
      'Hope ronnie goes on to win',
      'I hope both reach the final.',
      'This is an awesome match best of luck to both players',
      "Ronnie's greatest of all time,don't @ me",
      'John Higgins is not playing?',
      "It's always dream match go on Judd",
      'Not interested in Donald but will have a look for the rocket',
      'Rocket will play mark allen as usual',
      'Hey, I dont wanna click on that link, feels like im gonna catch a virus or something. What does it say?',
      'Ronnie vs E. Slessor is possible...',
      'Yesssss.....',
      'Trump vs Ronnie',
    ],
  },
  {
    post:
      'Peter Moor scored a 60-ball 92* to power Zimbabwe to a table-topping eight-wicket win against Singapore in the sixth match of the T20I tri-series.',
    comments: [
      'First pay your Electricity bills, Then come to the page. But Earthquake was fantastic.',
      'The speech waas fantastic tea was fantastic, 27 Feb was fantastic',
      'Moor! You should contribute more for zim!!',
      'Well played Moor!!',
      'He is the best cricketer.',
      'Zimbabwe power',
      'Zimbabwe father of Pakistan respect from la ilaha illallah',
      'Congratulations Zimbabwe, Love from Bangladesh',
      '370 most fantastic than any other issue',
      'Brilliant performance',
      'The speech day by day is more fantastic',
      'fantastic inning LoL',
      'Mig 21 was fantastic',
    ],
  },
  {
    post: "What a start to Gabriel Martinelli's Arsenal career",
    comments: [
      'Very sharp,paced and talented kid. He has a great future,we are lucky to have him in our great team.',
      "Martinelli is just one lucky Chap! At the same time very talented and blessed...he's a true Arsenal kind of a player! He's future is so bright May he be blessed with many goals!",
      'He is one of the players we have been missing at Arsenal. He has already proven his worthness.. All the best to Martinelli. We expect to see more of his inclusion in the first eleven',
      "Yes, outstanding performance, good lad. You needn't to adapt to the game like Pepe, from the very beginning you scored and score and score again. You give us a bright hope for tomorrow.",
      'We have got so many good young players...if we can keep hold of them we can be a force to reckon with in next years',
      'What a great start to hopefully a long journey at Arsenal! Emery needs to seriously consider him playing alongside Laca and Auba and benching Pepe',
      'Cabellos deserved an appreciation post for his excellent performance against Liege.',
      'Also To note Mustafi and Martinez have maintained three clean sheets this season',
      'This guy is very clinical in front of the goal!',
      'He is a poacher in front the goal. If managed properly he will become a great asset to Arsenal. Very important to keep big clubs away not to lure him.',
      'Could Martinelli be our next Bergkamp or I am overrating him! I like his approach to the game and the nose for goal. May he get better and better.',
      'He is simply the best youth player in this Arsenal team only if given the time he deserves everyone will know, we’ll see soon',
      'The header was wow.. Kieran Tirney crosses went to havard University.',
      'One more Brazilian boy shining in Europe. God bless him in this tough journey.',
    ],
  },
  {
    post: "We'll never forget when Sergio Aguero scored FIVE!",
    comments: [
      'Great to see that again. Travelled over from Ireland with my twins boys for their first city match. Sadly my father passed away later that night',
      'Excellent. Mcfc can make a beautiful history. Yes certainly can.',
      'He was my Fpl captain on that day ... I was faint with happiness after he scored the 5th...',
      'My son went for a hot dog and missed 3 of his goals.......',
      "There is racism in Man City of The players d'nt pass the ball to Mahrez.",
      "You'll never be Champions League winners.and never win again the premier League.you are one of the most wrost team in history.no team has never win Champions League only with money.Go on Reds.the premier League is ours this year.",
      'He was taken off with about 20 minutes left from memory could have got 6',
      'Remember that he was sub by 65min he would have scored more',
      'And he would have easily had the double hat trick if not taken off.... for that useless bony if I remember right lol',
      'Why did Pel take him off with 30 minutes left to play?',
      'Golden boot goat. Consistency is key and Aguero has it covered.',
      'He is not sergio Kun Aguero He Is Sergio Kun Dile',
      "Why didn't you do the same on Tuesday against Dinamo?",
    ],
  },
  {
    post: 'Going very nicely in Group C!',
    comments: [
      'amazing victory! come on City!',
      'Nice game yesterday, the guys and coaching crew did so well .good game let just keep it up ,man city on top',
      'Great performance by City. Wonderful goals by our substitutes Sterling and Jimmy Grimble in the flesh.',
      'Thanks our Team and City fans to support, Thanks God! Alhamdulillah..',
      "Good game good win I just notice the positioning of both cancelo and mahrez I don't know if pep was trying something different. Also Foden deserve more time his young but super good",
      'Another city player that you cannot take your eyes off is Rodri...his adaptation to the PL in such a short time speaks volumes of his quality..even in this early period one could clearly see the vision, class n composure in him...',
      "Great job even tho it was a bit boring (attack v defense) but we dominated and they knew from the first minute not to mess with us, I say we did great except those chances we missed, otherwise it would've an 8-0 or so",
      "I really don't understand why concentrating the play on the left wing while there's no efficacity on the attacks there ! Missing KDB in his switch style of play , good performance from Mahrez as always hope he'll keep it up",
      'Thank you to our two substitutes who made the scoresheet.',
      "again Riyad Mahrez magical touches he's the spirit returns to the team, but what I wonder how Mahrez passes Sterling and Sterling stingy?",
      'The man of the match is sterling.',
      'He enters the second half and saves the team.',
      'Mehrez plays against denamo Zagreb and against his teammates and disperses everyone with a Assist',
    ],
  },
  {
    post:
      'These two will push each other ALL the way. Watch Andy Murray v Dominic Thiem from Beijing on Friday on Tennis TV!',
    comments: [
      'Mate this is going to be a thriller',
      'Wow Chi è che vince a tennis Mi raccomando fatemi sapere revolti ayu palatennis',
      "Murray's back rege",
      'Well done Andy!',
      'Lang mae ur lum reek!',
      'Unbelievable, so amazing shots.',
      'inda mari aadunga da',
      "Murray's defensive style makes me puke",
      "je savais pas que c'était filmé à Lambersart",
      'Proof of how tennis can really be a mental game when the playing field is level. Such contrasts in their attitudes to adversity.',
      'Montreal battle better',
      'Agree, one of the best matches I’ve ever seen',
      'Really annoyed me this one. Murray shouldnt have let him come back. This wouldve taken their head to head to 8-8 but Djokovic went 9-7.',
    ],
  },
];
